kind: Service                             
apiVersion: v1
metadata:
  name: rky
  labels:
    app: rky
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: rky                    
  type: LoadBalancer                   